version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: always
    network_mode: bridge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /volumes/nginx-proxy/conf:/etc/nginx/conf.d
      - /volumes/nginx-proxy/vhost:/etc/nginx/vhost.d
      - /volumes/nginx-proxy/html:/usr/share/nginx/html
      - /volumes/nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    network_mode: bridge
    volumes_from:
      - nginx-proxy
    volumes:
      - /volumes/nginx-proxy/certs:/etc/nginx/certs:rw
      - /volumes/nginx-proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
