concurrent = 4
check_interval = 3

[session_server]
  session_timeout = 1800

[[runners]]
  name = "technat-cloud-runner"
  url = "https://code.immerda.ch"
  token = "rsxsHmzDkUmZ-ZzqsBCg"
  executor = "docker"
  limit = 2
  request_concurrency = 2
  [runners.custom_build_dir]
    [runners.cache]
    Type = "s3"
    Path = "technat_cloud"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "object.technat.cloud"
      BucketName = "gitlab-runner-cache"
      BucketLocation = "us-east-1"
      Insecure = false
      AuthenticationType = "access-key"
      AccessKey = "gitlab-runner-cache"
      SecretKey = "yPjwFLYkoxOgDXTktltgsUzBoeI2WtYrzU7pxJ4w"
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
