concurrent = 2
check_interval = 3

[session_server]
  session_timeout = 1800

[[runners]]
  name = "k8s-at-hetzner-runner-1"
  url = "https://code.immerda.ch"
  token = "n9dwguKzwKG4tbuzayoP"
  executor = "docker"
  limit = 2
  request_concurrency = 2
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Path = "k8s_at_hetzner"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "s3.technat.ch"
      BucketName = "gitlab-runner-cache"
      BucketLocation = "us-east-1"
      Insecure = false
      AuthenticationType = "access-key" 
      AccessKey = "gitlab-runner-cache"
      SecretKey = "yPjwFLYkoxOgDXTktltgsUzBoeI2WtYrzU7pxJ4w"
  [runners.docker] 
    tls_verify = false 
    image = "docker:stable" 
    privileged = false 
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0

[[runners]]
  name = "k8s-at-hetzner-runner-2"
  url = "https://code.immerda.ch"
  token = "GmPtRkjcH2DK6T8tKNLi"
  executor = "docker"
  limit = 2
  request_concurrency = 2
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Path = "k8s_at_hetzner"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "object.technat.cloud"
      BucketName = "gitlab-runner-cache"
      BucketLocation = "us-east-1"
      Insecure = false
      AuthenticationType = "access-key" 
      AccessKey = "gitlab-runner-cache"
      SecretKey = "yPjwFLYkoxOgDXTktltgsUzBoeI2WtYrzU7pxJ4w"
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0

[[runners]]
  name = "k8s-at-hetzner-runner-3"
  url = "https://code.immerda.ch"
  token = "J-M9btyBszB9yzbsA-2z"
  executor = "docker"
  limit = 2
  request_concurrency = 2
  [runners.custom_build_dir]
  [runners.cache]
    Type = "s3"
    Path = "k8s_at_hetzner"
    Shared = true
    [runners.cache.s3]
      ServerAddress = "object.technat.cloud"
      BucketName = "gitlab-runner-cache"
      BucketLocation = "us-east-1"
      Insecure = false
      AuthenticationType = "access-key" 
      AccessKey = "gitlab-runner-cache"
      SecretKey = "yPjwFLYkoxOgDXTktltgsUzBoeI2WtYrzU7pxJ4w"
  [runners.docker]
    tls_verify = false
    image = "docker:stable"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
