version: '3'

services:
  k8s-at-hetzner-runner:
    image: gitlab/gitlab-runner:latest
    container_name: k8s-at-hetzner-runner
    restart: always
    networks:
     - faultier
    deploy:
      resources:
        limits:
          memory: 512M
    volumes:
      - ./config/:/etc/gitlab-runner/
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  faultier:
    external: true
