version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    env_file:
      - .env # vaultwarden config (secure)
    environment:
      # proxy config
      VIRTUAL_HOST: vault.technat.dev
      LETSENCRYPT_HOST: vault.technat.dev
      VIRTUAL_PORT: 80
      # vaultwarden config
      SIGNUPS_ALLOWED: false
      SIGNUPS_VERIFY: true
      SIGNUPS_DOMAINS_WHITELIST: technat.ch
      TRASH_AUTO_DELETE_DAYS: 180
      INCOMPLETE_2FA_TIME_LIMIT: 3
      DOMAIN: https://vault.technat.dev
      LOGIN_RATELIMIT_SECONDS: 60
      LOGIN_RATELIMIT_MAX_BURST: 10
      AUTHENTICATOR_DISABLE_TIME_DRIFT: true
      SMTP_HOST: mail.infomaniak.com
      SMTP_FROM: vault@technat.ch
      SMTP_FROM_NAME: Technat's Vault
      SMTP_SECURITY: force_tls
      WEBSOCKET_ENABLED: true
    volumes:
      - /volumes/vaultwarden:/data/
    networks:
      - faultier

networks:
  faultier:
    external: true
