version: "3"

services:
  wiki:
    image: requarks/wiki:2
    container_name: jswiki
    volumes:
      - /volumes/jswiki/wiki.sqlite:/wiki/wiki.sqlite
    environment:
      DB_TYPE: sqlite
      DB_FILEPATH: /wiki/wiki.sqlite
      VIRTUAL_HOST: wiki.technat.cloud
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: wiki.technat.cloud
      LETSENCRYPT_EMAIL: root@technat.cloud
    restart: unless-stopped
    networks:
     - faultier

networks:
  faultier:
    external: true
