version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-06-30T20-58-09Z
  command: server --console-address "0.0.0.0:9001" http://minio{1...4}/data{1...2}
  restart: unless-stopped
  networks:
    - faultier
  expose:
    - "9000"
    - "9001"
  env_file:
    - .env
  environment:
    MINIO_BROWSER_REDIRECT_URL: https://s3-console.technat.ch
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - /volumes/minio/data1-1:/data1
      - /volumes/minio/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - /volumes/minio/data2-1:/data1
      - /volumes/minio/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - /volumes/minio/data3-1:/data1
      - /volumes/minio/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - /volumes/minio/data4-1:/data1
      - /volumes/minio/data4-2:/data2

  nginx:
    image: nginx:alpine
    hostname: nginx
    networks:
      - faultier
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: s3.technat.ch,s3-console.technat.ch
      LETSENCRYPT_HOST: s3.technat.ch,s3-console.technat.ch
      VIRTUAL_PORT: 9000
      LETSENCRYPT_SINGLE_DOMAIN_CERTS: true
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

networks:
  faultier:
    external: true
