version: '3.7'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2022-02-01T18-00-14Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  env_file:
    - .env
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    networks:
      - faultier
    volumes:
      - /volumes/minio/data1-1:/data1
      - /volumes/minio/data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    networks:
      - faultier
    volumes:
      - /volumes/minio/data2-1:/data1
      - /volumes/minio/data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    networks:
      - faultier
    volumes:
      - /volumes/minio/data3-1:/data1
      - /volumes/minio/data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    networks:
      - faultier
    volumes:
      - /volumes/minio/data4-1:/data1
      - /volumes/minio/data4-2:/data2

  nginx:
    image: nginx:alpine
    hostname: minio-nginx
    networks:
      - faultier
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: object.technat.cloud
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: object.technat.cloud
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  nginx-console:
    image: nginx:1.19.2-alpine
    hostname: nginx-console
    restart: always
    volumes:
      - ./nginx-console.conf:/etc/nginx/nginx.conf:ro
    environment:
      VIRTUAL_HOST: object-console.technat.cloud
      VIRTUAL_PORT: 9001
      LETSENCRYPT_HOST: object-console.technat.cloud
    networks:
      - faultier
    depends_on:
      - minio1
      - minio2
      - minio3



networks:
  faultier:
    external: true
